### ISSUE TITLE
LLU - LLU doesn't despawn

### ISSUE THREAD

**Issue by Dethdeath** [psforever/PSF-LoginServer#1019] opened 2023-02-06 22:31 UTC
LLU base A is hacked by NC, LLU needs to be delivered at base B.
Base B goes neutral, LLU doesn't despawn but can also not be used to capture the base anymore.

During the fight yesterday after the timer ran out it said TR failed to deliver the LLU, even though TR was not involved in this hack.
I have not been able to reproduce this 2nd part, it correctly says NC failed to deliver the LLU. So that may have been a fluke of some kind.

**Comment by Fate-JH** [comment] 2023-02-07 00:36
The second part is easy: the facility is neutral when it is resecured, so the message attempts to reflect that when it talks about the original faction resecuring it.  The default is the TR.

**Comment by Fate-JH** [comment] 2023-02-07 18:34
After re-reading, I might have misunderstood that these are separate incidents?  In any case, the logic error that I predicted in my reply is indeed committed by the code, even if the issue never arose before, and I have written a correction for it.

**Comment by Fate-JH** [comment] 2023-02-07 18:39
The first part of the original problem statement should not be an issue as long as the facility was not supplied with NTU.  A powerless facility is always neutral and will never be "captured".  If the issue is the facility is being supplied with power (NTU) again after losing power during an LLU hack, but the hack can not longer go through, I will reexamine the system as best that I can.

**Comment by Dethdeath** [comment] 2023-02-07 20:23
> After re-reading, I might have misunderstood that these are separate incidents? 

It all happened during the same hack.
The issue is that the linked NC base went neutral while the LLU was being moved towards it. At this point the hack should've failed instantly, but instead it didn't and the LLU didn't despawn either.

**Closed** 2023-02-14 05:09 UTC
