### ISSUE TITLE
Message storm causes large backlog and server fail over

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#404] opened 2020-05-02 18:54 UTC
When toggling the state of all bases on a continent, this creates a massive message storm leading to 99% until the message backlog is cleared. @NickPSF 

Here is the relevant Netdata posts:

**Overview**
![image](https://user-images.githubusercontent.com/14133344/80872958-4d144580-8c83-11ea-9954-606d839c9e56.png)

**UDP Errors** (indicates UDP queues are overflowing)
![image](https://user-images.githubusercontent.com/14133344/80872929-0f172180-8c83-11ea-8649-007eca9a5219.png)

Here is Kamon with Actor stats.

**Before incident**

![image](https://user-images.githubusercontent.com/14133344/80873097-29053400-8c84-11ea-98d1-89ab9cfd2fce.png)

**Incident Ramping up**
![image](https://user-images.githubusercontent.com/14133344/80873109-3de1c780-8c84-11ea-8410-6da3e744c0b4.png)

**Peak Incident**
![image](https://user-images.githubusercontent.com/14133344/80873123-4fc36a80-8c84-11ea-953b-b7f8a9546b13.png)

**Peak Incident mailbox times**
![image](https://user-images.githubusercontent.com/14133344/80873132-649ffe00-8c84-11ea-9d56-746487516fc5.png)

**Normal mailbox times before incident**
![image](https://user-images.githubusercontent.com/14133344/80873142-7d101880-8c84-11ea-8141-e2a8b1a48ce6.png)

**Comment by Mazo** [comment] 2020-06-28 12:42
Closing this since as far as I'm aware, the issue is resolved.

**Closed by Mazo** 2020-06-28 12:42 UTC
Labels: Bug, Critical, Fixed Not Regressed
